FROM ubuntu:18.04

LABEL maintainer="Christoph Mahnke"
LABEL description="FNFT/FNFTpy test environment ubuntu: 18.04"

RUN apt-get update
RUN apt-get install -y cmake git gfortran python3 python3-numpy
RUN git clone https://github.com/FastNFT/FNFT.git
RUN cd FNFT && mkdir build && cd build && cmake .. && make
RUN cd /
RUN cp FNFT/lib/libfnft.so.0.2.1 /usr/local/lib/
RUN git clone https://github.com/xmhk/FNFTpy.git
RUN cd FNFTpy && python3 run_tests.py


