FROM alpine:3.7
LABEL maintainer="Christoph Mahnke"
LABEL description="FNFT/FNFTpy test environment alpine "

RUN apk add gcc libc-dev cmake git gfortran make python3 py3-numpy
RUN git clone https://github.com/FastNFT/FNFT.git
RUN cd FNFT && mkdir build && cd build && cmake .. && make
RUN cd /
RUN cp FNFT/lib/libfnft.so /usr/local/lib/
RUN git clone https://github.com/xmhk/FNFTpy.git
RUN cd FNFTpy && python3 run_tests.py
# RUN cd FNFTpy && git checkout development && python3 run_tests.py